---
title           : "Beyond a static, between-person structure of personality"
shorttitle      : "My preregistration"
date            : "`r Sys.setlocale('LC_TIME', 'C'); format(Sys.time(), '%d\\\\. %B %Y')`"

author: 
  - name        : Emorie D Beck
    affiliation : Northwestern University Feinberg School of Medicine
  - name        : Alexander P Christensen
    affiliation : University of Pennsylvania
  - name        : David Clark
    affiliation : University of Michigan
  - name        : Daniel K Mroczek
    affiliation : Northwestern University, Northwestern University Feinberg School of Medicine
  - name        : Joshua J Jackson
    affiliation : Washington University in St. Louis

output: 
  html_document:
    theme: united
    highlight: tango
    df_print: paged
    code_folding: show
    toc: true
    toc_float: true
  
bibliography: r-references.bib
biblio-style: "apalike"
csl: "apa-6th-edition.csl"
---

# Study Information

## Title
<!-- Provide the working title of your study. It may be the same title that you submit for publication of your final manuscript, but it is not a requirement. The title should be a specific and informative description of a project. Vague titles such as 'Fruit fly preregistration plan' are not appropriate.

Example: Effect of sugar on brownie tastiness. -->

`r rmarkdown::metadata$title`

## Description
<!-- Please give a brief description of your study, including some background, the purpose of the of the study, or broad research questions. The description should be no longer than the length of an abstract. It can give some context for the proposed study, but great detail is not needed here for your preregistration.

Example: Though there is strong evidence to suggest that sugar affects taste preferences, the effect has never been demonstrated in brownies. Therefore, we will measure taste preference for four different levels of sugar concentration in a standard brownie recipe to determine if the effect exists in this pastry. -->

The structure of personality is one of the first (e.g., Allport, 1921, 1937; Stagner, 1937), most debated (the search for the “Big Few;” see Condon et al., 2020), and most consequential (e.g., the Big Five reified the relevance of personality for prediction and description and reduced jingle-jangle) topics in the study of personality. However, there are two main issues with previous approaches to understanding personality structure. First, almost the entirety of these findings are based on cross-sectional questionnaire data, with some extensions to longitudinal questionnaire data. Newer data collection methods such as intensive longitudinal assessments (ILA) provide a new window by which we can understand personality that is more aligned with theoretical thinking about the nature of personality both historically and modernly (see Beck & Jackson, 2020a, 2021, for an overview). Second, work on the structure of personality has overly relied on factor analyses of cross-sectional survey data to reduce individual differences to the Big Few. Such an approach ignores the history and theory of (1) idiographic approaches to personality (e.g., Allport, 1937, 1968; Cattell, 1947) and (2) personality dynamics (e.g., Allport, 1960; Rosenzweig, 1982). But new and longstanding statistical methods, like, multilevel modeling, dynamic systems approaches, network psychometrics, and item response theory, have promise for elucidating new ways of conceptualizing personality structure and linking it to dynamics and change.

To better understand personality structure, this study will use ILA of perhaps the most currently favored personality questionnaire of the Big Five, the Big Five Inventory II, administered to a sample of approximately 200 college students using a planned missing data approach four times per day for two weeks. Because there are many ways to conceptualize personality structure, we will test a number of analytic methods that represent some of the most dominant and popular methods for assessing structure at the present time in order to answer a number of questions about personality structure.

## Hypotheses
<!-- List specific, concise, and testable hypotheses. Please state if the hypotheses are directional or non-directional. If directional, state the direction. A predicted effect is also appropriate here. If a specific interaction or moderation is important to your research, you can list that as a separate hypothesis.

Example: If taste affects preference, then mean preference indices will be higher with higher concentrations of sugar. -->

### Between-Person  
1. What is the between-person trait structure (i.e. the R-technique structure) of personality using aggregated (imputed and unimputed) ILA data? Does this structure replicate the Big Five and correspond to cross-sectional surveys? In other words, do the items cover the latent trait and differentiate people?  
2. What is the between-person facet structure of personality using aggregated (imputed and unimputed) ILA data? Does this structure replicate the Big Five Facet structure in cross-sectional surveys? Or are people less/more differentiating when they fill out assessments in the moment?  

### Within-Person  
3. What is the within-person factor structure (i.e. the P-technique structure) of (imputed and unimputed) ILA data?  
4. How much variability is there across people in terms of number, content, loadings, variances, etc.? In other words, Are some people more or less faceted / can we look at complexity of people?  

# Design Plan  
<!-- In this section, you will be asked to describe the overall design of your study. Remember that this research plan is designed to register a single study, so if you have multiple experimental designs, please complete a separate preregistration. -->

## Study type

**Observational Study**. Data is collected from study subjects that are not randomly assigned to a treatment. This includes surveys, natural experiments, and regression discontinuity designs.

## Blinding
<!-- Blinding describes who is aware of the experimental manipulations within a study. Select all that apply. Is there any additional blinding in this study? -->

Although the data from these study come from the first wave of a longitudinal experiment, at this stage, there was no blinding as participants had not yet been assigned to an experimental group.  

## Study design
<!-- Describe your study design. Examples include two-group, factorial, randomized block, and repeated measures. Is it a between (unpaired), within-subject (paired), or mixed design? Describe any counterbalancing required. Typical study designs for observation studies include cohort, cross sectional, and case-control studies.

This question has a variety of possible answers. The key is for a researcher to be as detailed as is necessary given the specifics of their design. Be careful to determine if every parameter has been specified in the description of the study design. There may be some overlap between this question and the following questions. That is OK, as long as sufficient detail is given in one of the areas to provide all of the requested information. For example, if the study design describes a complete factorial, 2 X 3 design and the treatments and levels are specified previously, you do not have to repeat that information.

Example: We have a between subjects design with 1 factor (sugar by mass) with 4 levels. -->

The data for the present study are from the first wave of experience sampling data from a longitudinal personalized intervention study.  

## Randomization
<!-- If you are doing a randomized study, how will you randomize, and at what level? Typical randomization techniques include: simple, block, stratified, and adaptive covariate randomization. If randomization is required for the study, the method should be specified here, not simply the source of random numbers.

Example: We will use block randomization, where each participant will be randomly assigned to one of the four equally sized, predetermined blocks. The random number list used to create these four blocks will be created using the web applications available at https://random.org. -->

Item order in both the trait and state measures were randomized.  

In addition, state personality was measured using a planned missing data protocol. Participants received 15 out of 60 BFI-2 items at each time point, 3 from each trait at each time point to assure full covariance matrix coverage as well as equal coverage across traits. More details about the procedure and validity of this method are available on the Open Science Framework (https://osf.io/pj9sy/).  

# Sampling Plan
<!-- In this section we’ll ask you to describe how you plan to collect samples, as well as the number of samples you plan to collect and your rationale for this decision. Please keep in mind that the data described in this section should be the actual data used for analysis, so if you are using a subset of a larger dataset, please describe the subset that will actually be used in your study. -->

## Existing data
<!-- Preregistration is designed to make clear the distinction between confirmatory tests, specified prior to seeing the data, and exploratory analyses conducted after observing the data. Therefore, creating a research plan in which existing data will be used presents unique challenges. Please select the description that best describes your situation. Please do not hesitate to contact us if you have questions about how to answer this question (prereg@cos.io). -->

**Registration following analysis of the data**. As of the date of submission, you have accessed and analyzed some of the data relevant to the research plan. This includes preliminary analysis of variables, calculation of descriptive statistics, and observation of data distributions. Please see cos.io/prereg for more information.  

## Explanation of existing data
<!-- If you indicate that you will be using some data that already exist in this study, please describe the steps you have taken to assure that you are unaware of any patterns or summary statistics in the data. This may include an explanation of how access to the data has been limited, who has observed the data, or how you have avoided observing any analysis of the specific data you will use in your study.

An appropriate instance of using existing data would be collecting a sample size much larger than is required for the study, using a small portion of it to conduct exploratory analysis, and then registering one particular analysis that showed promising results. After registration, conduct the specified analysis on that part of the dataset that had not been investigated by the researcher up to that point.

Example: An appropriate instance of using existing data would be collecting a sample size much larger than is required for the study, using a small portion of it to conduct exploratory analysis, and then registering one particular analysis that showed promising results. After registration, conduct the specified analysis on that part of the dataset that had not been investigated by the researcher up to that point. -->

Emorie Beck and Joshua Jackson have previously worked with these data. Alex Christensen, David Clark, and Dan Mroczek have not. To mitigate this, each author made independent predictions about how results for different pre-planned analyses would turn out. Moreover, Emorie abstaind from predictions for which she had used a small subset of this sample for similar analyses previously. The data cleaning, analysis plan, and inferential tests have been detailed carefully and all deviations from the planned analyses will be included the final manuscript.  

We have not run any analyses using EGA, multilevel factor analysis, IRT, Neural Networks, LCA, total correlation, or NMI. Only EFA's of between and within-person data have been previously performed a subset of participants for a conference presentation (not published).  

## Data collection procedures
<!-- Please describe the process by which you will collect your data. If you are using human subjects, this should include the population from which you obtain subjects, recruitment efforts, payment for participation, how subjects will be selected for eligibility from the initial pool (e.g. inclusion and exclusion rules), and your study timeline. For studies that donÍt include human subjects, include information about how you will collect samples, duration of data gathering efforts, source or location of samples, or batch numbers you will use.

The answer to this question requires a specific set of instructions so that another person could repeat the data collection procedures and recreate the study population. Alternatively, if the study population would be unable to be reproduced because it relies on a specific set of circumstances unlikely to be recreated (e.g., a community of people from a specific time and location), the criteria and methods for creating the group and the rationale for this unique set of subjects should be clear.

Example: Participants will be recruited through advertisements at local pastry shops. Participants will be paid $10 for agreeing to participate (raised to $30 if our sample size is not reached within 15 days of beginning recruitment). Participants must be at least 18 years old and be able to eat the ingredients of the pastries. -->

Participants in this study were drawn from a larger study personality intervention study.

Participants responded to two types of surveys: trait and state (Experience Sampling Method; ESM) measures, for which they were paid separately. For the first wave, which is the only wave used in the present study, participants were recruited from the psychology subject pool at Washington University in St. Louis. Participants were told that the study posted on the recruitment website was the first wave of a longer longitudinal study they would be offered the opportunity to take part in.

Participants were brought into the lab between October 2018 and December 2019, where a research assistant or the first author explained the study procedure to them and walked them through the consent procedure. If they consented, participants were led to a room where they could fill out a form to opt into the ESM portion of the study. They then completed baseline trait measures using the Qualtrics Survey Platform. After, the participants were debriefed, paid \$10 in cash and, if they opted into the ESM portion of the study, the ESM survey procedure was explained to them. 

Participants then received ESM measures 4 times a day for a two weeks (max n = 56). The survey platform was built by the first author using the jsPsych library. Additional javascript controllers were written for the purpose of this study and are available on the first author's GitHub. Start times were based on times participants indicated they would like to receive their first survey. Surveys were sent every 4 hours, meaning that the surveys spanned a 12 hour period from the first time participants indicated. Participants received their first survey at their chosen time on the Monday following their in-lab session. They were compensated \$0.50 for each survey completed for a maximum of $28. To incentivize responding, participants who completed at least 50 surveys received a "bonus" for a total compensation of \$30, which was distributed as an Amazon Gift Card.

Additional waves of data were completed remotely online but will not be used in the present study. See Beck \& Jackson (2021) for an overview of additional data.  

## Sample size
<!-- Describe the sample size of your study. How many units will be analyzed in the study? This could be the number of people, birds, classrooms, plots, interactions, or countries included. If the units are not individuals, then describe the size requirements for each unit. If you are using a clustered or multilevel design, how many units are you collecting at each level of the analysis? For some studies, this will simply be the number of samples or the number of clusters. For others, this could be an expected range, minimum, or maximum number.

Example: Our target sample size is 280 participants. We will attempt to recruit up to 320, assuming that not all will complete the total task. -->

To date, 215 participants have taken part in the study, and 210 of these participants additionally agreed to take part in the ESM portion of the study. We will use a subset of these participants with at least 10 responses, which we anticipate to be at least 150.  

## Sample size rationale
<!-- This could include a power analysis or an arbitrary constraint such as time, money, or personnel. This gives you an opportunity to specifically state how the sample size will be determined. A wide range of possible answers is acceptable; remember that transparency is more important than principled justifications. If you state any reason for a sample size upfront, it is better than stating no reason and leaving the reader to "fill in the blanks." Acceptable rationales include: a power analysis, an arbitrary number of subjects, or a number based on time or monetary constraints.

Example: We used the software program G*Power to conduct a power analysis. Our goal was to obtain .95 power to detect a medium effect size of .25 at the standard .05 alpha error probability. -->

Participants were collected with two goals: validation of the ESM study procedure and as part of the larger intervention study. For the former, we oversampled the goals for the intervention study, which had a goal of N = 100. Data collection halted in spring 2020 because of COVID-19 and has not resumed as it requires in-person assessments.  

## Stopping rule
<!-- If your data collection procedures do not give you full control over your exact sample size, specify how you will decide when to terminate your data collection. 

You may specify a stopping rule based on p-values only in the specific case of sequential analyses with pre-specified checkpoints, alphas levels, and stopping rules. Unacceptable rationales include stopping based on p-values if checkpoints and stopping rules are not specified. If you have control over your sample size, then including a stopping rule is not necessary, though it must be clear in this question or a previous question how an exact sample size is attained.

Example: We will post participant sign-up slots by week on the preceding Friday night, with 20 spots posted per week. We will post 20 new slots each week if, on that Friday night, we are below 320 participants. -->

The main stopping rule was feasibility as COVID-19 made continued collection under the same set of procedures impossible.  

# Variables
<!-- In this section you can describe all variables (both manipulated and measured variables) that will later be used in your confirmatory analysis plan. In your analysis plan, you will have the opportunity to describe how each variable will be used. If you have variables which you are measuring for exploratory analyses, you are not required to list them, though you are permitted to do so. -->
A list of all variables, both measured and created, are included in a codebook attached with this preregistration.  

## Measured variables
<!-- Describe each variable that you will measure. This will include outcome measures, as well as any predictors or covariates that you will measure. You do not need to include any variables that you plan on collecting if they are not going to be included in the confirmatory analyses of this study.

Observational studies and meta-analyses will include only measured variables. As with the previous questions, the answers here must be precise. For example, 'intelligence,' 'accuracy,' 'aggression,' and 'color' are too vague. Acceptable alternatives could be 'IQ as measured by Wechsler Adult Intelligence Scale' 'percent correct,' 'number of threat displays,' and 'percent reflectance at 400 nm.'

Example: The single outcome variable will be the perceived tastiness of the single brownie each participant will eat. We will measure this by asking participants ‘How much did you enjoy eating the brownie’ (on a scale of 1-7, 1 being 'not at all', 7 being 'a great deal') and 'How good did the brownie taste' (on a scale of 1-7, 1 being 'very bad', 7 being 'very good'). -->

Measured variables include:  
- 60 personality indicators (15 facets, 5 traits) from the BFI-2  

## Indices
<!-- If any measurements are  going to be combined into an index (or even a mean), what measures will you use and how will they be combined? Include either a formula or a precise description of your method. If your are using a more complicated statistical method to combine measures (e.g. a factor analysis), you can note that here but describe the exact method in the analysis plan section.

If you are using multiple pieces of data to construct a single variable, how will this occur? Both the data that are included and the formula or weights for each measure must be specified. Standard summary statistics, such as "means" do not require a formula, though more complicated indices require either the exact formula or, if it is an established index in the field, the index must be unambiguously defined. For example, "biodiversity index" is too broad, whereas "Shannon’s biodiversity index" is appropriate.

Example: We will take the mean of the two questions above to create a single measure of 'brownie enjoyment.'  -->

Personality was measured in ESM surveys using the full BFI-2 (Soto \& John, 2017). For the purposes of the present study, items will be reversed scored and composited into their resulting 15 facets or left as raw 15 items.  

# Analysis Plan
<!-- You may describe one or more confirmatory analysis in this preregistration. Please remember that all analyses specified below must be reported in the final article, and any additional analyses must be noted as exploratory or hypothesis generating.

A confirmatory analysis plan must state up front which variables are predictors (independent) and which are the outcomes (dependent), otherwise it is an exploratory analysis. You are allowed to describe any exploratory work here, but a clear confirmatory analysis is required. -->

Below, we include a brief summary of the approaches that will be used to test each question. For each method, an additional supporting document written by the analyst for each method is included with this preregistration:  

- Emorie Beck - R- and P-technique exploratory factor analysis (EFA) using the `psych` package in `R`; latent class analysis using the `tidyLPA` package in `R`  
- Alex Christensen - R- and P-technique dynamic exploratory graph analysis (dynEGA), neural network test (NN), normalized mutual information (NMI), and total correlation (TC) using the `EGAnet` package in `R`
- David Clark - R- and P-technique exploratory factor analysis (EFA) and multilevel factor analysis in MPlus  
- Josh Jackson - Item Response Theory (IRT) using the `brms` pacakge in `R`.

## Question 1  
What is the between-person trait structure (i.e. the R-technique structure) of personality using aggregated (imputed and unimputed) ILA data? Does this structure replicate the Big Five and correspond to cross-sectional surveys? In other words, do the items cover the latent trait and differentiate people?        

- **EFA**:        Parallel analysis for choosing number with oblimin rotation using the `psych` package in `R` (aggregated; Emorie) and Mplus (aggregated & pooled; David)        
- **EGA**:        Use both aggregated data and within/between GLLA approaches (Alex)         
        **IRT**:        See if any items are poorly performing using brms (e.g., item discrimination values < .8); use both aggregated data and MLM forms (Josh)         
        **NN**:        Can we predict whether the data generating process is a factor model or a network model (Alex)        

## Question 2  
What is the between-person facet structure of personality using aggregated (imputed and unimputed) ILA data? Does this structure replicate the Big Five Facet structure in cross-sectional surveys? Or are people less/more differentiating when they fill out assessments in the moment?        

- **EFA**:        Parallel analysis for choosing number with oblimin rotation using the `psych` package in `R` (aggregated; Emorie) and Mplus (aggregated & pooled; David)  
- **EGA**:         Use both aggregated data and within/between GLLA approaches (Alex)  
- **IRT**: See if any items are poorly performing using brms (e.g., item discrimination values < .8); use both aggregated data and MLM forms (Josh)  
- **NN**:        Can we predict whether the data generating process is a factor model or a network model (NN = Neural Network)         

## Question 3  
What is the within-person factor structure (i.e. the P-technique structure) of (imputed and unimputed) ILA data?  

- **EFA**: Parallel analysis for choosing number with oblimin rotation using the `psych` package in `R` (Emorie) and Mplus (David)         
- **EGA**:        Network structure using GLLA and time delay embedding        (Alex)
- **IRT**:        See if any items are poorly performing using brms (e.g., item discrimination values < .8); use both aggregated data and MLM forms (Josh)         

## Question 4  
How much variability is there across people in terms of number, content, loadings, variances, etc.? In other words, Are some people more or less faceted / can we look at complexity of people?        

**(a)** Within-person structure: Distribution of factors        

- **EFA**: Results from Q3 EFA  
- **EGA**:         Results from Q3 EFA  

**(b)** Variability/complexity  

- Total correlation can be used as a measure of response pattern consistency across time  

**(c)** Within- and between-person match  

- **Normalized mutual information (NMI)** can be used to compare people’s within-person structure to the BFI-2’s theoretical between-person structure (e.g., a continuum from less alike to more alike)         
- **EFA**:        Comparing structure from Q1 EFA to Q3 EFA (e.g., eigenvalues, loadings)  
- **EGA**:        Comparing stricture from Q1 EGA to Q3 EGA (e.g., network loadings)  
- **IRT**:        IRT on people more or less similar to the BFI-2 theoretical structure  

**(d)** Variability across people  

- Using **NMI**, people can be compared to one another, forming a matrix that can be used for clustering based on similarity of structure        
- **EFA**: Comparing all individuals from Q3 EFA to each other; Use clustering techniques (e.g., k-means) to test for clusters of within-person structures across people  
- **EGA**: Comparing all individuals from Q3 EGA to each other; Use clustering techniques (e.g., k-means) to test for clusters of within-person structures across people  
- **IRT** IRT on groups of people with similar structures id'd by clustering techniques  

## Statistical models
<!-- What statistical model will you use to test each hypothesis? Please include the type of model (e.g. ANOVA, multiple regression, SEM, etc) and the specification of the model (this includes each variable that will be included as predictors, outcomes, or covariates). Please specify any interactions, subgroup analyses, pairwise or complex contrasts, or follow-up tests from omnibus tests. If you plan on using any positive controls, negative controls, or manipulation checks you may mention that here. Remember that any test not included here must be noted as an exploratory test in your final article.

This is perhaps the most important and most complicated question within the preregistration. As with all of the other questions, the key is to provide a specific recipe for analyzing the collected data. Ask yourself: is enough detail provided to run the same analysis again with the information provided by the user? Be aware for instances where the statistical models appear specific, but actually leave openings for the precise test. See the following examples:

- If someone specifies a 2x3 ANOVA with both factors within subjects, there is still flexibility with the various types of ANOVAs that could be run. Either a repeated measures ANOVA (RMANOVA) or a multivariate ANOVA (MANOVA) could be used for that design, which are two different tests. 
- If you are going to perform a sequential analysis and check after 50, 100, and 150 samples, you must also specify the p-values you’ll test against at those three points.

Example:  We will use a one-way between subjects ANOVA to analyze our results. The manipulated, categorical independent variable is 'sugar' whereas the dependent variable is our taste index. -->

The statistical models used in the present study represent three broad psychometric methods -- factor analysis, exploratory graph analysis, and item response theory models -- used at different levels of aggregation and by different analysts to answer different questions about the between- and within-person structure of personality and their relationship to one another.  

## Transformations {#transformations}
<!-- If you plan on transforming, centering, recoding the data, or will require a coding scheme for categorical variables, please describe that process. If any categorical predictors are included in a regression, indicate how those variables will be coded (e.g. dummy coding, summation coding, etc.) and what the reference category will be.

Example: The "Effect of sugar on brownie tastiness" does not require any additional transformations. However, if it were using a regression analysis and each level of sweet had been categorically described (e.g. not sweet, somewhat sweet, sweet, and very sweet), 'sweet' could be dummy coded with 'not sweet' as the reference category. -->

EGA transforms raw (level) personality state data into time delay embedded derivatives with four embedding dimensions using GLLA.  

## Inference criteria {#inference}
<!-- What criteria will you use to make inferences? Please describe the information youÍll use (e.g. p-values, bayes factors, specific model fit indices), as well as cut-off criterion, where appropriate. Will you be using one or two tailed tests for each of your analyses? If you are comparing multiple conditions or testing multiple hypotheses, will you account for this?

p-values, confidence intervals, and effect sizes are standard means for making an inference, and any level is acceptable, though some criteria must be specified in this or previous fields. Bayesian analyses should specify a Bayes factor or a credible interval. If you are selecting models, then how will you determine the relative quality of each? In regards to multiple comparisons, this is a question with few "wrong" answers. In other words, transparency is more important than any specific method of controlling the false discovery rate or false error rate. One may state an intention to report all tests conducted or one may conduct a specific correction procedure; either strategy is acceptable.

Example: We will use the standard p<.05 criteria for determining if the ANOVA and the post hoc test suggest that the results are significantly different from those expected if the null hypothesis were correct. The post-hoc Tukey-Kramer test adjusts for multiple comparisons. -->

Inferences differ based on the type of test, which rely on simulation, machine learning methods (i.e. regularization), and Bayesian sampling. In general, the following inference rule apply:  

- **EFA**: parallel analysis using the `psych` package in `R` as we apply it simulates random data and compares whether the scree plot of the observed data is greater than the 95\% interval of the random data. The number of extracted factors is based on the number that exceed these bounds in the scree plot.  
- **EGA**: EGA uses graphical least absolute shrinkage and selection operator (glasso) to estimate the elements in the correlation matrix that are non-spurious (i.e. prevents overfitting).  
- **IRT**: Inferences of Bayesian IRT models will be based on the 95\% credible interval (CI) of the target parameters in the posterior distribution.  

## Data exclusion
<!-- How will you determine what data or samples, if any, to exclude from your analyses? How will outliers be handled? Will you use any awareness check? Any rule for excluding a particular set of data is acceptable. One may describe rules for excluding a participant or for identifying outlier data.

Example: No checks will be performed to determine eligibility for inclusion besides verification that each subject answered each of the three tastiness indices. Outliers will be included in the analysis. -->

Participants with too little data at an ESM wave (N < 10) will be excluded.  

## Missing data
<!-- How will you deal with incomplete or missing data? Any relevant explanation is acceptable. As a final reminder, remember that the final analysis must follow the specified plan, and deviations must be either strongly justified or included as a separate, exploratory analysis.

Example: If a subject does not complete any of the three indices of tastiness, that subject will not be included in the analysis. -->

Because planned missing data meet missing at random (MAR) criterion, we will use multiple imputation as implemented in the `amelia` package in `R`. Previous work indicates that these imputed data show good between-person structure and strong convergence with both raw data and trait data (https://osf.io/pj9sy/).  

## Exploratory analyses (optional)
<!-- If you plan to explore your data set to look for unexpected differences or relationships, you may describe those tests here. An exploratory test is any test where a prediction is not made up front, or there are multiple possible tests that you are going to use. A statistically significant finding in an exploratory test is a great way to form a new confirmatory hypothesis, which could be registered at a later time.

Example: We expect that certain demographic traits may be related to taste preferences. Therefore, we will look for relationships between demographic variables (age, gender, income, and marital status) and the primary outcome measures of taste preferences. -->

Arguably, all analyses in the present study are exploratory as we make no formal directional hypotheses. Instead, each author made independent predictions about expectations for each question / method combination.  

# References
##
